# Generated by Django 3.2.7 on 2021-10-01 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cricket', '0001_initial'),
        ('members', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredteam',
            name='teamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.cricketteam'),
        ),
        migrations.AddField(
            model_name='pointstable',
            name='teams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.cricketteam'),
        ),
        migrations.AddField(
            model_name='pointstable',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.crickettournament'),
        ),
        migrations.AddField(
            model_name='notification',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.cricketteam'),
        ),
        migrations.AddField(
            model_name='matchstatistics',
            name='matchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.matchschedule'),
        ),
        migrations.AddField(
            model_name='matchschedule',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.crickettournament'),
        ),
        migrations.AddField(
            model_name='matchschedule',
            name='teams',
            field=models.ManyToManyField(to='members.CricketTeam'),
        ),
        migrations.AddField(
            model_name='matchplayedbyteam',
            name='Tosswin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tosswin', to='members.cricketteam'),
        ),
        migrations.AddField(
            model_name='matchplayedbyteam',
            name='battingteam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battingteam', to='members.cricketteam'),
        ),
        migrations.AddField(
            model_name='matchplayedbyteam',
            name='firstteam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstteam', to='members.cricketteam'),
        ),
        migrations.AddField(
            model_name='matchplayedbyteam',
            name='matchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.matchschedule'),
        ),
        migrations.AddField(
            model_name='matchplayedbyteam',
            name='secondteam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondteam', to='members.cricketteam'),
        ),
        migrations.AddField(
            model_name='crickettournament',
            name='scorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
