# Generated by Django 3.2.7 on 2021-10-11 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField(default=15)),
                ('speciality', models.CharField(max_length=32)),
                ('playerimage', models.ImageField(null=True, upload_to='playersimage')),
            ],
            options={
                'verbose_name_plural': 'Participant',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('contactno', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Training',
            },
        ),
        migrations.CreateModel(
            name='CricketTeam',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cricket.customuser')),
                ('teamname', models.CharField(max_length=32)),
                ('logo', models.ImageField(default='cricketteamlogo/logo.png', upload_to='cricketteamlogo')),
                ('captain_name', models.CharField(max_length=32)),
                ('contactno', models.IntegerField(default=0)),
                ('manager', models.CharField(max_length=32)),
                ('coach', models.CharField(max_length=32)),
                ('participant', models.ManyToManyField(to='members.Participant')),
            ],
            options={
                'verbose_name_plural': 'CricketTeam',
            },
        ),
    ]
