# Generated by Django 3.2.7 on 2021-10-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cricketteam',
            options={'verbose_name_plural': 'CricketTeams'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={},
        ),
        migrations.AddField(
            model_name='training',
            name='batch',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='training',
            name='rollno',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='training',
            name='section',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
