# Generated by Django 3.2.7 on 2021-10-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20211012_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='rollno',
            new_name='roll_number',
        ),
    ]
